### ISSUE TITLE
我是vue3的项目，vue的版本是3.2.37，然后是webpack4，安装你的插件的时候，出现了错误

### ISSUE THREAD

**Issue by KBKUN024** [sherwinshen/vue3-text-clamp#1]
![image](https://user-images.githubusercontent.com/54589019/187642871-f4a0d1dc-3e48-4618-b93a-c9540bdc356c.png)
而我所做的，仅仅是写了这句代码:
![image](https://user-images.githubusercontent.com/54589019/187642978-7433b3c9-52cf-461c-86c7-57fdd238c1db.png)
说我的loader有问题，请问您知道，我应该使用什么loader吗?

**Comment by KBKUN024** [comment]
不管是全局导入还是在组件内按需导入，都有这个问题

**Comment by KBKUN024** [comment]
顺带一提，我的项目是使用js写的，不是ts，不知道有没有影响

**Comment by sherwinshen** [comment]
我看了下报错的地方是有?.的语法，应该项目不支持es6的特性，需要处理下。也许你可以试一下vue.config.js文件里加一行transpileDependencies: ['/vue3-text-clamp/']

**Comment by KBKUN024** [comment]
好的，谢谢你啦，我去试一下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Sherwin ***@***.***&gt;
发送时间: 2022年9月3日 12:31
收件人: sherwinshen/vue3-text-clamp ***@***.***&gt;
抄送: KBKUN024 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [sherwinshen/vue3-text-clamp] 我是vue3的项目，vue的版本是3.2.37，然后是webpack4，安装你的插件的时候，出现了错误 (Issue #1)





 
我看了下报错的地方是有?.的语法，应该项目不支持es6的特性，需要处理下。也许你可以试一下vue.config.js文件里加一行transpileDependencies: ['/vue3-text-clamp/']

**Comment by KBKUN024** [comment]
好像行不通



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Sherwin ***@***.***&gt;
发送时间: 2022年9月3日 12:31
收件人: sherwinshen/vue3-text-clamp ***@***.***&gt;
抄送: KBKUN024 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [sherwinshen/vue3-text-clamp] 我是vue3的项目，vue的版本是3.2.37，然后是webpack4，安装你的插件的时候，出现了错误 (Issue #1)





 
我看了下报错的地方是有?.的语法，应该项目不支持es6的特性，需要处理下。也许你可以试一下vue.config.js文件里加一行transpileDependencies: ['/vue3-text-clamp/']

**Comment by KBKUN024** [comment]
我加了你说的那句代码，但是只要在main.js一import就会报之前那个错误



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Sherwin ***@***.***&gt;
发送时间: 2022年9月3日 12:31
收件人: sherwinshen/vue3-text-clamp ***@***.***&gt;
抄送: KBKUN024 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [sherwinshen/vue3-text-clamp] 我是vue3的项目，vue的版本是3.2.37，然后是webpack4，安装你的插件的时候，出现了错误 (Issue #1)





 
我看了下报错的地方是有?.的语法，应该项目不支持es6的特性，需要处理下。也许你可以试一下vue.config.js文件里加一行transpileDependencies: ['/vue3-text-clamp/']

**Comment by s90180007** [comment]
I have the same error (
