### ISSUE TITLE
location  start, 显示文本内容有误

### ISSUE THREAD

**Issue by geshichuangdi** [sherwinshen/vue3-text-clamp#5]
![image](https://user-images.githubusercontent.com/44060829/236453489-a872ec0c-579d-4817-8568-278654090db9.png)
location  start, 应该把文本最后的内容显示出来  把前面的内容省略, 目前只是页面上在前面显示省略号, 显示的文本内容还是文本前面部分

**Comment by geshichuangdi** [comment]
应该显示的内容是
...when used in combination with modern tooling and supporting libraries.
才对吧

**Comment by sherwinshen** [comment]
fixed, you can use @0.1.2
